

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "email": "user.email@gmail.com",
    "password": "yourpassword"
  }
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "user.email@gmail.com",
    "password": "yourpassword"
    
}



###
DELETE  http://localhost:3000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNjZmNzQ3NDZiY2M5Mzk2NjFiZDA2MjQ2IiwiZXhwIjoxNzI3NTY4MzgwfQ.90cYmIXfVGDuqLaVwhaCxPz31_LGmiWGqLhLxm6Y8zM






